name: cktgen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.12.31
  - certifi=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=22.3.1
  - python=3.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.4.2
      - colorlog==6.9.0
      - cycler==0.11.0
      - diffusers==0.11.1
      - filelock==3.12.2
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - greenlet==3.1.1
      - huggingface-hub==0.16.4
      - idna==3.10
      - igraph==0.10.8
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - mako==1.2.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - numpy==1.21.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-ml-py==12.570.86
      - optuna==4.0.0
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - psutil==7.0.0
      - pygraphviz==1.7
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - regex==2024.4.16
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - six==1.17.0
      - sqlalchemy==2.0.42
      - texttable==1.7.0
      - threadpoolctl==3.1.0
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - zipp==3.15.0
